#! /usr/bin/env bash

shopt -s extglob

declare -a debian_current_suites=(
  'unstable'
  'testing'
  'stable'
  'oldstable'
  'oldoldstable'
  'sid'
  'trixie'
  'bookworm'
  'bullseye'
  'buster'
  'stretch'
)

declare -a debian_obsolete_suites=(
  'oldoldoldstable'
  'jessie'
)

declare debian_current_mirror='https://deb.debian.org/debian'

declare debian_ports_mirror='https://deb.debian.org/debian-ports'

declare debian_obsolete_mirror='http://archive.debian.org/debian'

declare -a ubuntu_current_suites=(
  'devel'
  'lunar'   # 23.04
  'kinetic' # 22.10
  'jammy'   # 22.04 LTS
  'focal'   # 20.04 LTS
  'bionic'  # 18.04 LTS
  'xenial'  # 16.04 LTS
  'trusty'  # 14.04 LTS
)

declare -a ubuntu_obsolete_suites=(
  'impish'  # 21.10
  'hirsute' # 21.04
  'groovy'  # 20.10
  'eoan'    # 19.10
  'disco'   # 19.04
  'cosmic'  # 18.10
  'artful'  # 17.10
  'zesty'   # 17.04
  'yakkety' # 16.10
  'wily'    # 15.10
  'vivid'   # 15.04
  'utopic'  # 14.10
  'saucy'   # 13.10
  'raring'  # 13.04
  'quantal' # 12.10
  'precise' # 12.04 LTS
)

declare ubuntu_current_mirror='http://archive.ubuntu.com/ubuntu'

declare ubuntu_ports_mirror='http://ports.ubuntu.com/ubuntu-ports'

declare ubuntu_obsolete_mirror='https://old-releases.ubuntu.com/ubuntu'

function check_primary_suite {
  case "$1" in
    @($(echo "${debian_current_suites[@]} ${debian_obsolete_suites[@]} ${ubuntu_current_suites[@]} ${ubuntu_obsolete_suites[@]}" | tr ' ' '|'))) ;;
    *) return 1 ;;
  esac
}

function default_output_file_name {
  case "$1" in
    @($(echo "${debian_current_suites[@]} ${debian_obsolete_suites[@]}" | tr ' ' '|'))) echo "Debian_$1_$2_$(date +'%Yy-%mm-%dd')" ;;
    @($(echo "${ubuntu_current_suites[@]} ${ubuntu_obsolete_suites[@]}" | tr ' ' '|'))) echo "Ubuntu_$1_$2_$(date +'%Y-%m-%d')" ;;
  esac
}

function default_mirrors {
  case "$1" in
    @($(echo "${debian_current_suites[@]}" | tr ' ' '|')))
      case "$2" in
        amd64 | arm64 | armel | armhf | i386 | mips64el | mipsel | ppc64el | s390x) echo "$debian_current_mirror" ;;
        *) echo "$debian_ports_mirror" ;;
      esac
      ;;
    @($(echo "${debian_obsolete_suites[@]}" | tr ' ' '|'))) echo "$debian_obsolete_mirror" ;;
    @($(echo "${ubuntu_current_suites[@]}" | tr ' ' '|')))
      case "$2" in
        amd64 | i386) echo "$ubuntu_current_mirror" ;;
        *) echo "$ubuntu_ports_mirror" ;;
      esac
      ;;
    @($(echo "${ubuntu_obsolete_suites[@]}" | tr ' ' '|'))) echo "$ubuntu_obsolete_mirror" ;;
  esac
}

function default_hostname {
  case "$1" in
    @($(echo "${debian_current_suites[@]} ${debian_obsolete_suites[@]}" | tr ' ' '|'))) echo 'debian' ;;
    @($(echo "${ubuntu_current_suites[@]} ${ubuntu_obsolete_suites[@]}" | tr ' ' '|'))) echo 'ubuntu' ;;
  esac
}

function case_specific_packages {
  case "$1" in
    essential | custom) ;;
    *)
      echo 'ca-certificates'
      case "$2" in
        stretch | jessie | oldoldstable | oldoldoldstable | zesty | yakkety | xenial | wily | vivid | utopic | trusty | saucy | raring | quantal | precise)
          echo 'apt-transport-https'
          ;;
      esac
      ;;
  esac
}

# see https://wiki.debian.org/Teams/Dpkg/FAQ#broken-usrmerge

function default_merged_usr {
  case "$1" in
    @($(echo "${debian_current_suites[@]} ${debian_obsolete_suites[@]}" | tr ' ' '|')))
      case "$2" in
        # Debian releases keep the variant 'buildd' split-usr by default.
        buildd)
          echo 'none'
          ;;
        *)
          case "$1" in
            # merged-usr blacklist for past Debian releases.
            stretch | jessie | oldoldstable | oldoldoldstable)
              echo 'none'
              ;;
            *)
              echo 'aliased-dirs'
              ;;
          esac
          ;;
      esac
      ;;
    @($(echo "${ubuntu_current_suites[@]} ${ubuntu_obsolete_suites[@]}" | tr ' ' '|')))
      case "$1" in
        # merged-usr blacklist for past Ubuntu releases.
        groovy | focal | eoan | disco | cosmic | bionic | artful | zesty | yakkety | xenial | wily | vivid | utopic | trusty | saucy | raring | quantal | precise)
          echo 'none'
          ;;
          # for hirsute keep the variant 'buildd' split-usr by default and merged-usr for all other variants.
        hirsute)
          case "$2" in
            buildd)
              echo 'none'
              ;;
            *)
              echo 'aliased-dirs'
              ;;
          esac
          ;;
        *)
          echo 'aliased-dirs'
          ;;
      esac
      ;;
  esac
}
